name: Calculate Version
on:
  workflow_call:
    outputs:
      version_string:
        description: "The calculated version string (YY.M.D)"
        value: ${{ jobs.calculate.outputs.version_string }}

jobs:
  calculate:
    runs-on: ubuntu-latest
    outputs:
      version_string: ${{ steps.calc.outputs.VERSION }}
    steps:
      - id: calc
        run: |
          DATE=$(date +'%y.%-m.%-d')
          HOUR=$(date +'%H')
          MIN=$(date +'%M')
          RC_MINS=$(( 10#$HOUR * 60 + 10#$MIN ))
          echo "VERSION=${DATE}-rc.${RC_MINS}" >> $GITHUB_OUTPUT
