name: Daily Final Version
on:
  workflow_call:
    inputs:
      plugin_slug:
        description: 'The directory name the plugin should have'
        required: false
        type: string

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version_string: ${{ steps.calc.outputs.VERSION }}
    steps:
      - id: calc
        run: |
          VERSION=$(date +'%y.%-m.%-d')
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

  update-source:
    needs: get-version
    uses: HalloftheGods/.github/.github/workflows/wp-plugin-update.yml@main
    with:
      version_string: ${{ needs.get-version.outputs.version_string }}

  release-zip:
    needs: [get-version, update-source]
    uses: HalloftheGods/.github/.github/workflows/build-plugin-zip.yml@main
    with:
      plugin_slug: ${{ inputs.plugin_slug != '' && inputs.plugin_slug || github.event.repository.name }}
      version: ${{ needs.get-version.outputs.version_string }}

  finalize:
    needs: release-zip
    uses: HalloftheGods/.github/.github/workflows/finalize-rc-releases.yml@main
